<?php

namespace ContainerCU9kxcZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Q1EeZWh.App\Entity\Validation' shared service.
     *
     * @return \App\Entity\Validation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q1EeZWh": it references class "App\\Entity\\Validation" but no such service exists.');
    }
}
