<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6yj3xN7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6yj3xN7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6yj3xN7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colisRecRepository' => ['privates', 'App\\Repository\\ColisRecRepository', 'getColisRecRepositoryService', true],
            'documentexpeditionRepository' => ['privates', 'App\\Repository\\DocumentexpeditionRepository', 'getDocumentexpeditionRepositoryService', true],
        ], [
            'colisRecRepository' => 'App\\Repository\\ColisRecRepository',
            'documentexpeditionRepository' => 'App\\Repository\\DocumentexpeditionRepository',
        ]);
    }
}
