<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TuLzBbrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tuLzBbr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tuLzBbr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'VehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'VehiculeRepository' => 'App\\Repository\\VehiculeRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
