<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_950jLGgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.950jLGg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.950jLGg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gift' => ['privates', '.errored..service_locator.950jLGg.App\\Entity\\Gifts', NULL, 'Cannot autowire service ".service_locator.950jLGg": it references class "App\\Entity\\Gifts" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'gift' => 'App\\Entity\\Gifts',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
