<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9coHmtTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9coHmtT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9coHmtT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cadeauxRepository' => ['privates', 'App\\Repository\\GiftsRepository', 'getGiftsRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'qrbuilder' => ['privates', 'Endroid\\QrCode\\Builder\\Builder', 'getBuilderService', true],
        ], [
            'cadeauxRepository' => 'App\\Repository\\GiftsRepository',
            'paginator' => '?',
            'qrbuilder' => '?',
        ]);
    }
}
