<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XmP8qOqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xmP8qOq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xmP8qOq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cadeauxRepository' => ['privates', 'App\\Repository\\GiftsRepository', 'getGiftsRepositoryService', true],
            'gifts' => ['privates', '.errored..service_locator.xmP8qOq.App\\Entity\\Gifts', NULL, 'Cannot autowire service ".service_locator.xmP8qOq": it references class "App\\Entity\\Gifts" but no such service exists.'],
            'qrbuilder' => ['privates', 'Endroid\\QrCode\\Builder\\Builder', 'getBuilderService', true],
        ], [
            'cadeauxRepository' => 'App\\Repository\\GiftsRepository',
            'gifts' => 'App\\Entity\\Gifts',
            'qrbuilder' => '?',
        ]);
    }
}
