<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYbTuvEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pYbTuvE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pYbTuvE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnoncesRepository', 'getAnnoncesRepositoryService', true],
            'colisRecRepository' => ['privates', 'App\\Repository\\ColisRecRepository', 'getColisRecRepositoryService', true],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnoncesRepository',
            'colisRecRepository' => 'App\\Repository\\ColisRecRepository',
        ]);
    }
}
