<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3RqGaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R3_rqGa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R3_rqGa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coli' => ['privates', '.errored..service_locator.R3_rqGa.App\\Entity\\Colis', NULL, 'Cannot autowire service ".service_locator.R3_rqGa": it references class "App\\Entity\\Colis" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'coli' => 'App\\Entity\\Colis',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
