<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Utc135VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Utc135V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Utc135V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colis' => ['privates', '.errored..service_locator.Utc135V.App\\Entity\\Colis', NULL, 'Cannot autowire service ".service_locator.Utc135V": it references class "App\\Entity\\Colis" but no such service exists.'],
        ], [
            'colis' => 'App\\Entity\\Colis',
        ]);
    }
}
