<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZSELq3_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zSELq3.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zSELq3.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'user' => ['privates', '.errored..service_locator.zSELq3..App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.zSELq3.": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'Normalizer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
