<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DeAQzf8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DeAQzf8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DeAQzf8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comp' => ['privates', '.errored..service_locator.DeAQzf8.App\\Entity\\Competition', NULL, 'Cannot autowire service ".service_locator.DeAQzf8": it references class "App\\Entity\\Competition" but no such service exists.'],
            'competitionRepository' => ['privates', 'App\\Repository\\CompetitionRepository', 'getCompetitionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'comp' => 'App\\Entity\\Competition',
            'competitionRepository' => 'App\\Repository\\CompetitionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
