<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonces2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ECpDOfk.App\Entity\Annonces' shared service.
     *
     * @return \App\Entity\Annonces
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ECpDOfk": it references class "App\\Entity\\Annonces" but no such service exists.');
    }
}
