<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S8.Ozi0.App\Entity\Colis' shared service.
     *
     * @return \App\Entity\Colis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S8.Ozi0": it references class "App\\Entity\\Colis" but no such service exists.');
    }
}
