<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentexpeditionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Q3jtqTx.App\Entity\Documentexpedition' shared service.
     *
     * @return \App\Entity\Documentexpedition
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q3jtqTx": it references class "App\\Entity\\Documentexpedition" but no such service exists.');
    }
}
