<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGiftsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.950jLGg.App\Entity\Gifts' shared service.
     *
     * @return \App\Entity\Gifts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.950jLGg": it references class "App\\Entity\\Gifts" but no such service exists.');
    }
}
