<?php

namespace ContainerKicfle5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizQuestionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.08e3V3S.App\Entity\QuizQuestion' shared service.
     *
     * @return \App\Entity\QuizQuestion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.08e3V3S": it references class "App\\Entity\\QuizQuestion" but no such service exists.');
    }
}
