<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKicfle5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKicfle5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKicfle5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKicfle5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKicfle5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kicfle5',
    'container.build_id' => 'c8ebb480',
    'container.build_time' => 1683558606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKicfle5');
