<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNZloUNd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNZloUNd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNZloUNd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNZloUNd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNZloUNd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NZloUNd',
    'container.build_id' => '05f330e9',
    'container.build_time' => 1710939217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNZloUNd');
